export const mockInfluencers = [
  {
    id: "inf_1",
    name: "Sophie Martin",
    bio: "Passionnée de mode et lifestyle parisien. Créatrice de contenu depuis 5 ans.",
    photo: "https://i.pravatar.cc/300?img=47",
    instagram: "@sophiemartin",
    tiktok: "@sophiemartin",
    youtube: "SophieMartin",
    followers: 85000,
    engagementRate: 4.2,
    category: "MACRO",
    interests: ["Mode", "Lifestyle", "Beauté"],
    gender: "Femme",
    country: "France",
    languages: ["Français", "Anglais"],
    ratePost: 800,
    rateStory: 200,
    rateVideo: 1500,
    isVerified: true,
    isActive: true,
    isPublic: true,
    subscription: "PRO",
    balance: 2450,
    userId: "user_inf_1",
  },
  {
    id: "inf_2",
    name: "Lucas Dubois",
    bio: "Créateur de contenu fitness & nutrition. Coach certifié.",
    photo: "https://i.pravatar.cc/300?img=11",
    instagram: "@lucasdubois_fit",
    tiktok: "@lucasdubois",
    followers: 145000,
    engagementRate: 5.8,
    category: "MACRO",
    interests: ["Fitness", "Nutrition", "Sport"],
    gender: "Homme",
    country: "France",
    languages: ["Français"],
    ratePost: 1200,
    rateStory: 350,
    rateVideo: 2500,
    isVerified: true,
    isActive: true,
    isPublic: true,
    subscription: "PRO",
    balance: 5800,
    userId: "user_inf_2",
  },
  {
    id: "inf_3",
    name: "Emma Laurent",
    bio: "Influenceuse voyage et gastronomie. J'explore le monde pour vous.",
    photo: "https://i.pravatar.cc/300?img=32",
    instagram: "@emmalaurent_travel",
    youtube: "EmmaLaurentTravel",
    followers: 320000,
    engagementRate: 3.1,
    category: "MACRO",
    interests: ["Voyage", "Gastronomie", "Culture"],
    gender: "Femme",
    country: "France",
    languages: ["Français", "Anglais", "Espagnol"],
    ratePost: 3500,
    rateStory: 800,
    rateVideo: 6000,
    isVerified: true,
    isActive: true,
    isPublic: true,
    subscription: "PRO",
    balance: 12300,
    userId: "user_inf_3",
  },
  {
    id: "inf_4",
    name: "Thomas Bernard",
    bio: "Tech enthusiast et gamer. Reviews honnêtes et contenu tech.",
    photo: "https://i.pravatar.cc/300?img=15",
    instagram: "@thomastech",
    youtube: "ThomasBernardTech",
    tiktok: "@thomastech",
    followers: 58000,
    engagementRate: 6.5,
    category: "MACRO",
    interests: ["Tech", "Gaming", "Innovation"],
    gender: "Homme",
    country: "France",
    languages: ["Français", "Anglais"],
    ratePost: 600,
    rateStory: 150,
    rateVideo: 1200,
    isVerified: false,
    isActive: true,
    isPublic: true,
    subscription: "FREE",
    balance: 890,
    userId: "user_inf_4",
  },
  {
    id: "inf_5",
    name: "Camille Petit",
    bio: "Micro-influenceuse beauté naturelle et skincare. Authenticité avant tout.",
    photo: "https://i.pravatar.cc/300?img=44",
    instagram: "@camillepetit_beauty",
    tiktok: "@camillebeauty",
    followers: 8500,
    engagementRate: 8.9,
    category: "MICRO",
    interests: ["Beauté", "Skincare", "Bien-être"],
    gender: "Femme",
    country: "France",
    languages: ["Français"],
    ratePost: 150,
    rateStory: 50,
    rateVideo: 300,
    isVerified: false,
    isActive: true,
    isPublic: true,
    subscription: "FREE",
    balance: 340,
    userId: "user_inf_5",
  },
  {
    id: "inf_6",
    name: "Alexandre Roy",
    bio: "Business, motivation et entrepreneuriat. Speaker international.",
    photo: "https://i.pravatar.cc/300?img=52",
    instagram: "@alexroy_business",
    youtube: "AlexandreRoy",
    followers: 680000,
    engagementRate: 2.8,
    category: "PERSONNALITE",
    interests: ["Business", "Motivation", "Entrepreneuriat"],
    gender: "Homme",
    country: "France",
    languages: ["Français", "Anglais"],
    ratePost: 8000,
    rateStory: 2000,
    rateVideo: 15000,
    isVerified: true,
    isActive: true,
    isPublic: true,
    subscription: "PRO",
    balance: 45000,
    userId: "user_inf_6",
  },
  {
    id: "inf_7",
    name: "Léa Fontaine",
    bio: "Mode, luxe et lifestyle. Ambassadrice de marques premium.",
    photo: "https://i.pravatar.cc/300?img=29",
    instagram: "@leafontaine",
    tiktok: "@leafontaine",
    followers: 1200000,
    engagementRate: 3.4,
    category: "PERSONNALITE",
    interests: ["Mode", "Luxe", "Voyage"],
    gender: "Femme",
    country: "France",
    languages: ["Français", "Anglais", "Italien"],
    ratePost: 20000,
    rateStory: 5000,
    rateVideo: 40000,
    isVerified: true,
    isActive: true,
    isPublic: true,
    subscription: "PRO",
    balance: 98000,
    userId: "user_inf_7",
  },
  {
    id: "demo_inf",
    name: "Marie Dupont",
    bio: "Influenceuse lifestyle et mode. Basée à Paris.",
    photo: "https://i.pravatar.cc/300?img=25",
    instagram: "@mariedupont",
    tiktok: "@mariedupont",
    followers: 25000,
    engagementRate: 4.7,
    category: "MACRO",
    interests: ["Mode", "Lifestyle", "Beauté"],
    gender: "Femme",
    country: "France",
    languages: ["Français", "Anglais"],
    ratePost: 400,
    rateStory: 100,
    rateVideo: 800,
    isVerified: true,
    isActive: true,
    isPublic: true,
    subscription: "PRO",
    balance: 1250,
    userId: "influencer-1",
  },
]

export const mockCampaigns = [
  {
    id: "camp_1",
    brandProfileId: "brand_1",
    brandName: "L'Oréal Paris",
    title: "Lancement Rouge à Lèvres Collection Automne",
    description: "Promotion de notre nouvelle collection de rouges à lèvres automne/hiver 2024.",
    budget: 15000,
    budgetRemaining: 8500,
    startDate: "2024-09-01",
    endDate: "2024-11-30",
    targetGender: "Femme",
    targetInterests: ["Beauté", "Mode", "Lifestyle"],
    targetCountries: ["France"],
    targetLanguages: ["Français"],
    targetCategory: "MACRO",
    status: "ACTIVE",
    promoCode: "LOREAL20",
    websiteUrl: "https://loreal.fr",
    autoAssign: false,
    influencersCount: 5,
    createdAt: "2024-08-15",
  },
  {
    id: "camp_2",
    brandProfileId: "brand_2",
    brandName: "Nike France",
    title: "Campagne Running Hiver 2024",
    description: "Mise en avant de notre nouvelle collection running pour l'hiver.",
    budget: 25000,
    budgetRemaining: 15000,
    startDate: "2024-10-01",
    endDate: "2024-12-31",
    targetGender: null,
    targetInterests: ["Sport", "Fitness", "Running"],
    targetCountries: ["France", "Belgique"],
    targetLanguages: ["Français"],
    targetCategory: "MACRO",
    status: "ACTIVE",
    promoCode: "NIKE15",
    websiteUrl: "https://nike.fr",
    autoAssign: true,
    influencersCount: 8,
    createdAt: "2024-09-20",
  },
  {
    id: "camp_3",
    brandProfileId: "brand-1",
    brandName: "Maison Élégance",
    title: "Campagne Mode Automne",
    description: "Campagne de mise en avant de notre collection automne.",
    budget: 5000,
    budgetRemaining: 3200,
    startDate: "2024-10-15",
    endDate: "2024-12-15",
    targetGender: "Femme",
    targetInterests: ["Mode", "Lifestyle"],
    targetCountries: ["France"],
    targetLanguages: ["Français"],
    targetCategory: "MICRO",
    status: "ACTIVE",
    promoCode: "MAISON10",
    websiteUrl: "https://maison-elegance.fr",
    autoAssign: false,
    influencersCount: 3,
    createdAt: "2024-10-01",
  },
]

export const mockTransactions = [
  {
    id: "tx_1",
    userId: "brand-1",
    type: "DEPOSIT",
    amount: 5000,
    description: "Rechargement portefeuille",
    createdAt: "2024-10-01",
  },
  {
    id: "tx_2",
    userId: "brand-1",
    type: "CAMPAIGN_PAYMENT",
    amount: -1800,
    description: "Paiement campagne: Campagne Mode Automne",
    createdAt: "2024-10-15",
  },
  {
    id: "tx_3",
    userId: "influencer-1",
    type: "CAMPAIGN_PAYMENT",
    amount: 400,
    description: "Rémunération campagne: Campagne Mode Automne",
    createdAt: "2024-10-20",
  },
  {
    id: "tx_4",
    userId: "influencer-1",
    type: "WITHDRAWAL",
    amount: -200,
    description: "Virement bancaire",
    createdAt: "2024-10-25",
  },
]

export const mockProposals = [
  {
    id: "prop_1",
    campaignId: "camp_1",
    campaignTitle: "Lancement Rouge à Lèvres Collection Automne",
    brandName: "L'Oréal Paris",
    payment: 800,
    status: "PENDING",
    createdAt: "2024-10-15",
    description: "Nous recherchons des créateurs de contenu beauté pour promouvoir notre nouvelle collection.",
  },
  {
    id: "prop_2",
    campaignId: "camp_2",
    campaignTitle: "Campagne Running Hiver 2024",
    brandName: "Nike France",
    payment: 400,
    status: "ACCEPTED",
    createdAt: "2024-10-10",
    description: "Rejoignez notre campagne running pour présenter notre nouvelle collection hiver.",
  },
]

export const mockMissions = [
  {
    id: "miss_1",
    campaignId: "camp_3",
    campaignTitle: "Campagne Mode Automne",
    brandName: "Maison Élégance",
    payment: 400,
    status: "ACCEPTED",
    deadline: "2024-12-01",
    instructions: "Créer un post Instagram et 2 stories présentant nos produits avec le code MAISON10.",
    postUrl: null,
    createdAt: "2024-10-15",
  },
]

export const mockBrands = [
  {
    id: "brand_1",
    companyName: "L'Oréal Paris",
    logo: "https://i.pravatar.cc/300?img=60",
    website: "https://loreal.fr",
    description: "Leader mondial de la beauté depuis 1909. Marque référente en cosmétique et soin.",
    sector: "Beauté & Cosmétique",
    balance: 45000,
    campaignsCount: 12,
    isPublic: true,
    country: "France",
    userId: "user_brand_1",
  },
  {
    id: "brand_2",
    companyName: "Nike France",
    logo: "https://i.pravatar.cc/300?img=61",
    website: "https://nike.fr",
    description: "Just Do It. Équipements sportifs de référence mondiale.",
    sector: "Sport & Mode",
    balance: 125000,
    campaignsCount: 8,
    isPublic: true,
    country: "France",
    userId: "user_brand_2",
  },
  {
    id: "brand_3",
    companyName: "Sézane",
    logo: "https://i.pravatar.cc/300?img=62",
    website: "https://sezane.com",
    description: "Mode française éthique et intemporelle. Née à Paris en 2013.",
    sector: "Mode",
    balance: 28000,
    campaignsCount: 5,
    isPublic: true,
    country: "France",
    userId: "user_brand_3",
  },
  {
    id: "brand_4",
    companyName: "Maison Kitsuné",
    logo: "https://i.pravatar.cc/300?img=63",
    website: "https://maisonkitsune.com",
    description: "Lifestyle brand parisienne alliant mode et musique.",
    sector: "Luxe & Lifestyle",
    balance: 67000,
    campaignsCount: 3,
    isPublic: true,
    country: "France",
    userId: "user_brand_4",
  },
  {
    id: "brand-1",
    companyName: "Maison Élégance",
    logo: null,
    website: "https://maison-elegance.fr",
    description: "Mode et élégance française. Collections capsule artisanales.",
    sector: "Mode",
    balance: 3200,
    campaignsCount: 1,
    isPublic: true,
    country: "France",
    userId: "brand-1",
  },
]

// ─── ÉVÉNEMENTS ───────────────────────────────────────────────────────────────
export const mockEvents = [
  {
    id: "evt_1",
    name: "Paris Fashion Week Independants",
    slug: "paris-fashion-week-independants",
    photo: "https://i.pravatar.cc/300?img=10",
    coverImage: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80&auto=format&fit=crop",
    description: "Festival dédié aux créateurs de mode indépendants. 3 jours de défilés, expositions et networking au Palais de Tokyo.",
    type: "Festival",
    sector: "Mode & Luxe",
    location: "Paris, France",
    eventDate: "2026-09-28",
    endDate: "2026-09-30",
    expectedAttendees: 5000,
    budget: 80000,
    sponsorshipGoal: 30000,
    sponsorshipRaised: 12000,
    isPublic: true,
    status: "OPEN",
    tags: ["Mode", "Fashion", "Paris", "Indépendants"],
    contactEmail: "contact@pfw-independants.fr",
    website: "https://pfw-independants.fr",
    userId: "user_evt_1",
    createdAt: "2026-01-10",
  },
  {
    id: "evt_2",
    name: "Tech For Good Summit 2026",
    slug: "tech-for-good-summit-2026",
    photo: "https://i.pravatar.cc/300?img=12",
    coverImage: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&q=80&auto=format&fit=crop",
    description: "Conférence internationale réunissant entrepreneurs, investisseurs et activistes du numérique responsable.",
    type: "Conférence",
    sector: "Tech & Innovation",
    location: "Lyon, France",
    eventDate: "2026-08-15",
    endDate: "2026-08-16",
    expectedAttendees: 2000,
    budget: 45000,
    sponsorshipGoal: 20000,
    sponsorshipRaised: 8500,
    isPublic: true,
    status: "OPEN",
    tags: ["Tech", "Innovation", "RSE", "Numérique"],
    contactEmail: "hello@techforgood.fr",
    website: "https://techforgood.fr",
    userId: "user_evt_2",
    createdAt: "2026-01-20",
  },
  {
    id: "evt_3",
    name: "Festival Gastronomia",
    slug: "festival-gastronomia",
    photo: "https://i.pravatar.cc/300?img=33",
    coverImage: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&q=80&auto=format&fit=crop",
    description: "Le plus grand festival gastronomique de la Côte d'Azur. Chefs étoilés, ateliers culinaires et marché producteurs.",
    type: "Festival",
    sector: "Gastronomie",
    location: "Nice, France",
    eventDate: "2026-07-18",
    endDate: "2026-07-20",
    expectedAttendees: 15000,
    budget: 120000,
    sponsorshipGoal: 50000,
    sponsorshipRaised: 35000,
    isPublic: true,
    status: "OPEN",
    tags: ["Gastronomie", "Cuisine", "Chefs", "Festival"],
    contactEmail: "sponsors@gastronomia.fr",
    website: "https://gastronomia.fr",
    userId: "user_evt_3",
    createdAt: "2025-12-05",
  },
  {
    id: "evt_4",
    name: "AfroBeats Paris Night",
    slug: "afrobeats-paris-night",
    photo: "https://i.pravatar.cc/300?img=14",
    coverImage: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800&q=80&auto=format&fit=crop",
    description: "Grande soirée musicale célébrant l'Afrobeats, l'Afropop et les sonorités africaines contemporaines à Paris.",
    type: "Concert",
    sector: "Musique & Culture",
    location: "Paris, France",
    eventDate: "2026-07-10",
    endDate: "2026-07-10",
    expectedAttendees: 3000,
    budget: 60000,
    sponsorshipGoal: 25000,
    sponsorshipRaised: 18000,
    isPublic: true,
    status: "OPEN",
    tags: ["Musique", "Afrobeats", "Concert", "Culture"],
    contactEmail: "contact@afrobeats-paris.fr",
    website: "https://afrobeats-paris.fr",
    userId: "user_evt_4",
    createdAt: "2026-02-01",
  },
  {
    id: "evt_5",
    name: "Run For Life Marathon",
    slug: "run-for-life-marathon",
    photo: "https://i.pravatar.cc/300?img=51",
    coverImage: "https://images.unsplash.com/photo-1452626038306-9aae5e071dd3?w=800&q=80&auto=format&fit=crop",
    description: "Marathon caritatif au profit de la recherche contre le cancer. Parcours urbain traversant Paris.",
    type: "Sport",
    sector: "Sport & Santé",
    location: "Paris, France",
    eventDate: "2026-10-04",
    endDate: "2026-10-04",
    expectedAttendees: 8000,
    budget: 35000,
    sponsorshipGoal: 15000,
    sponsorshipRaised: 4000,
    isPublic: true,
    status: "OPEN",
    tags: ["Sport", "Caritatif", "Running", "Santé"],
    contactEmail: "sponsors@runforlife.fr",
    website: "https://runforlife.fr",
    userId: "user_evt_5",
    createdAt: "2026-03-15",
  },
  {
    id: "demo_evt",
    name: "Connexion Festival 2026",
    slug: "connexion-festival-2026",
    photo: "https://i.pravatar.cc/300?img=35",
    coverImage: "https://images.unsplash.com/photo-1501281668745-f7f57925c3b4?w=800&q=80&auto=format&fit=crop",
    description: "Festival de networking entre créateurs, marques et investisseurs. 2 jours d'ateliers, conférences et soirées.",
    type: "Networking",
    sector: "Business & Influence",
    location: "Bordeaux, France",
    eventDate: "2026-11-20",
    endDate: "2026-11-21",
    expectedAttendees: 1200,
    budget: 25000,
    sponsorshipGoal: 10000,
    sponsorshipRaised: 0,
    isPublic: true,
    status: "OPEN",
    tags: ["Networking", "Créateurs", "Business"],
    contactEmail: "event@demo.com",
    website: "https://connexion-festival.fr",
    userId: "event-1",
    createdAt: "2026-04-01",
  },
]

// ─── NOUVEAUX PROJETS ─────────────────────────────────────────────────────────
export const mockProjects = [
  {
    id: "proj_1",
    name: "Bloom — App bien-être",
    slug: "bloom-app-bien-etre",
    photo: "https://i.pravatar.cc/300?img=41",
    coverImage: "https://images.unsplash.com/photo-1545205597-3d9d02c29597?w=800&q=80&auto=format&fit=crop",
    description: "Application mobile de méditation et bien-être mental avec IA personnalisée. Nous cherchons des ambassadeurs influenceurs et des sponsors pour notre lancement en septembre.",
    type: "Application mobile",
    sector: "Bien-être & Santé",
    stage: "Pré-lancement",
    launchDate: "2026-09-01",
    teamSize: 4,
    budget: 50000,
    sponsorshipGoal: 20000,
    sponsorshipRaised: 5000,
    isPublic: true,
    status: "OPEN",
    tags: ["Bien-être", "App", "IA", "Méditation"],
    contactEmail: "hello@bloom-app.fr",
    website: "https://bloom-app.fr",
    userId: "user_proj_1",
    createdAt: "2026-01-15",
  },
  {
    id: "proj_2",
    name: "Roots — Mode éthique",
    slug: "roots-mode-ethique",
    photo: "https://i.pravatar.cc/300?img=42",
    coverImage: "https://images.unsplash.com/photo-1558769132-cb1aea458c5e?w=800&q=80&auto=format&fit=crop",
    description: "Marque de vêtements 100% recyclés fabriqués en France. Lancement d'une collection capsule avec Kickstarter.",
    type: "Marque",
    sector: "Mode Éthique",
    stage: "Crowdfunding",
    launchDate: "2026-08-01",
    teamSize: 2,
    budget: 30000,
    sponsorshipGoal: 15000,
    sponsorshipRaised: 9200,
    isPublic: true,
    status: "OPEN",
    tags: ["Mode", "Éthique", "France", "Recyclé"],
    contactEmail: "roots@ethique.fr",
    website: "https://roots-mode.fr",
    userId: "user_proj_2",
    createdAt: "2026-02-10",
  },
  {
    id: "proj_3",
    name: "Cuisine en Série — Web-série",
    slug: "cuisine-en-serie",
    photo: "https://i.pravatar.cc/300?img=48",
    coverImage: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&q=80&auto=format&fit=crop",
    description: "Web-série culinaire en 10 épisodes avec des chefs émergents de France. Recherche partenaires médias et sponsors alimentaires.",
    type: "Contenu médias",
    sector: "Gastronomie & Médias",
    stage: "Production",
    launchDate: "2026-10-15",
    teamSize: 6,
    budget: 80000,
    sponsorshipGoal: 40000,
    sponsorshipRaised: 22000,
    isPublic: true,
    status: "OPEN",
    tags: ["Cuisine", "Vidéo", "Chefs", "Contenu"],
    contactEmail: "prod@cuisineenserie.fr",
    website: "https://cuisineenserie.fr",
    userId: "user_proj_3",
    createdAt: "2026-01-28",
  },
  {
    id: "proj_4",
    name: "SolarKit — Énergie accessible",
    slug: "solarkit-energie-accessible",
    photo: "https://i.pravatar.cc/300?img=57",
    coverImage: "https://images.unsplash.com/photo-1509391366360-2e959784a276?w=800&q=80&auto=format&fit=crop",
    description: "Kit solaire plug-and-play pour appartements. Rend l'énergie solaire accessible à tous sans installation.",
    type: "Startup Hardware",
    sector: "Énergie & Écologie",
    stage: "Seed",
    launchDate: "2026-07-20",
    teamSize: 5,
    budget: 200000,
    sponsorshipGoal: 60000,
    sponsorshipRaised: 15000,
    isPublic: true,
    status: "OPEN",
    tags: ["Solaire", "Écologie", "Startup", "Innovation"],
    contactEmail: "invest@solarkit.fr",
    website: "https://solarkit.fr",
    userId: "user_proj_4",
    createdAt: "2026-03-05",
  },
  {
    id: "demo_proj",
    name: "DotCast — Podcast Influence",
    slug: "dotcast-podcast-influence",
    photo: "https://i.pravatar.cc/300?img=43",
    coverImage: "https://images.unsplash.com/photo-1478737270239-2f02b77fc618?w=800&q=80&auto=format&fit=crop",
    description: "Podcast hebdomadaire sur le marketing d'influence : interviews de créateurs, marques et experts. Recherche sponsors pour la saison 2.",
    type: "Podcast",
    sector: "Médias & Marketing",
    stage: "Saison 2",
    launchDate: "2026-09-15",
    teamSize: 2,
    budget: 15000,
    sponsorshipGoal: 8000,
    sponsorshipRaised: 2500,
    isPublic: true,
    status: "OPEN",
    tags: ["Podcast", "Marketing", "Influence", "Médias"],
    contactEmail: "project@demo.com",
    website: "https://dotcast.fr",
    userId: "project-1",
    createdAt: "2026-04-10",
  },
]

// ─── SYSTÈME DE COLLABORATIONS / PROPOSITIONS ──────────────────────────────
export const mockCollaborations = [
  {
    id: "collab_1",
    fromId: "demo_inf",
    fromName: "Marie Dupont",
    fromType: "INFLUENCER",
    fromPhoto: "https://i.pravatar.cc/300?img=25",
    toId: "brand-1",
    toName: "Maison Élégance",
    toType: "BRAND",
    title: "Proposition de partenariat Mode",
    message: "Bonjour, je serais ravie de promouvoir votre collection automne auprès de mes 25k abonnés. Je propose 2 posts Instagram + 4 stories avec code promo exclusif.",
    type: "PAID",
    price: 500,
    counterPrice: null,
    status: "PENDING",
    createdAt: "2026-04-01",
  },
  {
    id: "collab_2",
    fromId: "brand-1",
    fromName: "Maison Élégance",
    fromType: "BRAND",
    fromPhoto: null,
    toId: "inf_5",
    toName: "Camille Petit",
    toType: "INFLUENCER",
    title: "Collaboration produits skincare",
    message: "Nous aimerions vous envoyer notre nouvelle gamme skincare en échange d'un post et 2 stories authentiques.",
    type: "PRODUCT",
    price: 0,
    counterPrice: null,
    status: "ACCEPTED",
    createdAt: "2026-03-20",
  },
  {
    id: "collab_3",
    fromId: "evt_1",
    fromName: "Paris Fashion Week Independants",
    fromType: "EVENT",
    fromPhoto: "https://i.pravatar.cc/300?img=10",
    toId: "inf_1",
    toName: "Sophie Martin",
    toType: "INFLUENCER",
    title: "Ambassadrice Fashion Week",
    message: "Nous serions honorés que vous soyez notre ambassadrice pour la prochaine édition. Accès VIP + rémunération + visibilité.",
    type: "AMBASSADOR",
    price: 3000,
    counterPrice: null,
    status: "NEGOTIATION",
    createdAt: "2026-03-25",
  },
]

// ─── OPPORTUNITÉS URGENTES (pour la home) ─────────────────────────────────
export const mockOpportunities = [
  ...mockEvents.map(e => ({
    id: e.id,
    type: 'EVENT' as const,
    name: e.name,
    photo: e.photo,
    description: e.description,
    deadline: e.eventDate,
    location: e.location,
    sector: e.sector,
    sponsorshipGoal: e.sponsorshipGoal,
    sponsorshipRaised: e.sponsorshipRaised,
    tags: e.tags,
    slug: e.slug,
  })),
  ...mockProjects.map(p => ({
    id: p.id,
    type: 'PROJECT' as const,
    name: p.name,
    photo: p.photo,
    description: p.description,
    deadline: p.launchDate,
    location: null,
    sector: p.sector,
    sponsorshipGoal: p.sponsorshipGoal,
    sponsorshipRaised: p.sponsorshipRaised,
    tags: p.tags,
    slug: p.slug,
  })),
].sort((a, b) => new Date(a.deadline).getTime() - new Date(b.deadline).getTime())

export const DEMO_USERS = {
  admin: {
    id: "admin-1",
    email: "admin@dotthetalents.com",
    password: "admin123",
    role: "ADMIN",
    name: "Administrateur",
  },
  brand: {
    id: "brand-1",
    email: "marque@demo.com",
    password: "demo123",
    role: "BRAND",
    name: "Maison Élégance",
    brandProfileId: "brand-1",
  },
  influencer: {
    id: "influencer-1",
    email: "influenceur@demo.com",
    password: "demo123",
    role: "INFLUENCER",
    name: "Sofia Martini",
    influencerProfileId: "demo_inf",
  },
  event: {
    id: "event-1",
    email: "evenement@demo.com",
    password: "demo123",
    role: "EVENT",
    name: "Connexion Festival",
    eventProfileId: "demo_evt",
  },
  project: {
    id: "project-1",
    email: "projet@demo.com",
    password: "demo123",
    role: "PROJECT",
    name: "DotCast Podcast",
    projectProfileId: "demo_proj",
  },
}
